repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.8
    hooks:
      - id: ruff
        name: "ruff sort imports"
        args:
          - "--fix"
          - "--select=I"
        alias: isort
      - id: ruff-format
      # Commands above are both formatters an not linters
      # See also: https://github.com/astral-sh/ruff/discussions/7310#discussioncomment-7102010
      - id: ruff
        name: "ruff lint"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        exclude: "docs"
        additional_dependencies: ["types-all"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        files: ".py|.rst"

  - repo: https://github.com/rhysd/actionlint
    rev: "v1.7.1"
    hooks:
      - id: actionlint
