name: "Run Tests"

on:
  push:
    branches-ignore:
      - "dependabot/**"
      - "sourcery/**"
      - "pre-commit-ci-update-config"
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * 5"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  test-pyglotaran-examples:
    needs: [pre-commit]
    uses: ./.github/workflows/test-pyglotaran-examples.yml
