name: "Test pyglotaran examples"

on:
  workflow_call:

jobs:
  self-consistency:
    name: Self consistency test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pyglotaran-validation
        uses: actions/checkout@v3
      - name: Checkout compare results to comparison-results
        uses: actions/checkout@v3
        with:
          repository: "glotaran/pyglotaran-examples"
          ref: comparison-results
          path: comparison-results

      - name: Copy comparison-results to comparison-results-current
        run: cp -r comparison-results comparison-results-current

      - name: Run result validator
        uses: ./
        with:
          validation_name: pyglotaran-examples

  create-example-list:
    name: Create Example List
    runs-on: ubuntu-latest
    needs: [self-consistency]
    outputs:
      example-list: ${{ steps.create-example-list.outputs.example-list }}
    steps:
      - name: Set example list output
        id: create-example-list
        uses: glotaran/pyglotaran-examples@main
        with:
          example_name: set example list
          set_example_list: true

  run-examples:
    name: "Run Example: "
    runs-on: ubuntu-latest
    needs: [create-example-list]
    strategy:
      matrix:
        example_name: ${{fromJson(needs.create-example-list.outputs.example-list)}}
    steps:
      - name: Checkout pyglotaran main branch
        uses: actions/checkout@v3
        with:
          repository: "glotaran/pyglotaran"
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pyglotaran
        run: |
          pip install wheel
          pip install -r requirements_dev.txt
          pip install .
      - name: ${{ matrix.example_name }}
        id: example-run
        uses: glotaran/pyglotaran-examples@main
        with:
          example_name: ${{ matrix.example_name }}
      - name: Installed packages
        if: always()
        run: |
          pip freeze
      - name: Upload Example Plots Artifact
        uses: actions/upload-artifact@v3
        with:
          name: example-plots
          path: ${{ steps.example-run.outputs.plots-path }}

      - name: Upload Example Results
        uses: actions/upload-artifact@v3
        with:
          name: example-results
          path: ~/pyglotaran_examples_results

  compare-results:
    name: Compare Results
    runs-on: ubuntu-latest
    needs: [run-examples]
    steps:
      - name: Checkout pyglotaran-validation
        uses: actions/checkout@v3
      - name: Checkout compare results
        uses: actions/checkout@v3
        with:
          repository: "glotaran/pyglotaran-examples"
          ref: comparison-results
          path: comparison-results

      - name: Download result artifact
        uses: actions/download-artifact@v3
        with:
          name: example-results
          path: comparison-results-current

      - name: Show used versions for result creation
        run: |
          echo "::group:: ✔️ Compare-Results"
          echo "✔️ pyglotaran-examples commit: $(< comparison-results/example_commit_sha.txt)"
          echo "✔️ pyglotaran commit: $(< comparison-results/pyglotaran_commit_sha.txt)"
          echo "::endgroup::"
          echo "::group:: ♻️ Current-Results"
          echo "♻️ pyglotaran-examples commit: $(< comparison-results-current/example_commit_sha.txt)"
          echo "::endgroup::"

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run result validator
        uses: ./
        with:
          validation_name: pyglotaran-examples

      - name: Remove comparison-results
        run: |
          rm -rf comparison-results
          cp -r comparison-results-current comparison-results

      - name: Test validator new result parsing
        uses: ./
        with:
          validation_name: pyglotaran-examples
